# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "homeassistant/aarch64-base-python:3.9-alpine3.13"
  amd64: "homeassistant/amd64-base-python:3.9-alpine3.13"
  armhf: "homeassistant/armhf-base-python:3.9-alpine3.13"
  armv7: "homeassistant/armv7-base-python:3.9-alpine3.13"
  i386: "homeassistant/i386-base-python:3.9-alpine3.13"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Mate 3 UDP Bridge"
  org.opencontainers.image.description: "Add-on to parse the Mate3 UDP data stream to Home Assistant."
  org.opencontainers.image.source: "https://github.com/home-assistant/addons-example"
  org.opencontainers.image.licenses: "Apache License 2.0"
args:
  TEMPIO_VERSION: "2021.09.0"
