# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Outback Power Mate3 data stream bridge
version: "0.1.0"
slug: mate3_bridge
description: Outback Power Mate3 data stream add-on for Home Assistant
url: "https://github.com/pgwipeout/mate3-bridge"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
  debug: false
  interface: "0.0.0.0"
  port: 57027
ports:
  57027/udp: 57027
schema:
  debug: bool
  interface: str?
  port: int?
image: "ghcr.io/home-assistant/{arch}-addon-example"
startup: "application"
boot: "auto"

