# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Outback Power Mate3 data stream bridge
version: "0.2.6"
slug: mate3_bridge
description: Outback Power Mate3 data stream add-on for Home Assistant
url: "https://github.com/pgwipeout/mate3-bridge"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
options:
  debug: false
  interface: "0.0.0.0"
  port: 57027
  mqtt_host: "127.0.0.1"
  mqtt_port: 1883
  mqtt_username: ""
  mqtt_password: ""
  discovery: "homeassistant"
  relay: false
  relay_host: ""
  relay_port: 57027
ports:
  57027/udp: 57027
schema:
  debug: bool
  interface: str?
  port: int?
  mqtt_host: str?
  mqtt_port: int?
  mqtt_username: str?
  mqtt_password: str?
  discovery: str?
  relay: bool
  relay_host: str?
  relay_port: int?
#image: "ghcr.io/pgwipeout/mate3_bridge-{arch}"
startup: "application"
boot: "auto"

